"use client";

import { useState } from "react";
import jsPDF from "jspdf";

type Persona = {
  name: string;
  role: string;
  goals: string[];
  frustrations: string[];
};

type ScreenItem = {
  name: string;
  purpose: string;
  wireframe_elements: string[];
};

type UserStory = {
  story: string;
  acceptance_criteria: string[];
};

type Metric = {
  name: string;
  description: string;
  target: string;
};

export type ExportData = {
  title: string;
  summary?: string;
  problemStatement?: string;
  goals: string[];
  personas: Persona[];
  userFlow: string[];
  screens: ScreenItem[];
  prd?: { overview: string; scope: string; requirements: string[] };
  userStories: UserStory[];
  metrics: Metric[];
};

const PAGE_WIDTH = 210; // A4 width in mm
const MARGIN = 18;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const PAGE_HEIGHT = 297; // A4 height in mm

export default function ExportPdfButton({ data }: { data: ExportData }) {
  const [generating, setGenerating] = useState(false);

  function handleExport() {
    setGenerating(true);

    const doc = new jsPDF({ unit: "mm", format: "a4" });
    let y = MARGIN;

    function ensureSpace(lineHeight: number) {
      if (y + lineHeight > PAGE_HEIGHT - MARGIN) {
        doc.addPage();
        y = MARGIN;
      }
    }

    function addHeading(text: string, size: number) {
      ensureSpace(size / 2 + 4);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(size);
      doc.text(text, MARGIN, y);
      y += size / 2 + 3;
    }

    function addParagraph(text: string) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      const lines = doc.splitTextToSize(text, CONTENT_WIDTH);
      lines.forEach((line: string) => {
        ensureSpace(6);
        doc.text(line, MARGIN, y);
        y += 6;
      });
      y += 3;
    }

    function addBulletList(items: string[]) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      items.forEach((item) => {
        const lines = doc.splitTextToSize(`•  ${item}`, CONTENT_WIDTH);
        lines.forEach((line: string) => {
          ensureSpace(6);
          doc.text(line, MARGIN, y);
          y += 6;
        });
      });
      y += 3;
    }

    // Title page
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text(data.title, MARGIN, y);
    y += 12;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(120);
    doc.text("Generated by WirePilot AI", MARGIN, y);
    doc.setTextColor(0);
    y += 12;

    if (data.summary) {
      addHeading("Product Summary", 14);
      addParagraph(data.summary);
    }

    if (data.problemStatement) {
      addHeading("Problem Statement", 14);
      addParagraph(data.problemStatement);
    }

    if (data.goals.length > 0) {
      addHeading("Goals", 14);
      addBulletList(data.goals);
    }

    if (data.personas.length > 0) {
      addHeading("User Personas", 14);
      data.personas.forEach((p) => {
        addHeading(`${p.name} — ${p.role}`, 12);
        addParagraph(`Goals: ${p.goals?.join("; ")}`);
        addParagraph(`Frustrations: ${p.frustrations?.join("; ")}`);
      });
    }

    if (data.userFlow.length > 0) {
      addHeading("User Flow", 14);
      addBulletList(data.userFlow);
    }

    if (data.screens.length > 0) {
      addHeading("Screens & Wireframes", 14);
      data.screens.forEach((s) => {
        addHeading(s.name, 12);
        addParagraph(s.purpose);
        addBulletList(s.wireframe_elements ?? []);
      });
    }

    if (data.prd) {
      addHeading("Product Requirements Document (PRD)", 14);
      addParagraph(`Overview: ${data.prd.overview}`);
      addParagraph(`Scope: ${data.prd.scope}`);
      addBulletList(data.prd.requirements ?? []);
    }

    if (data.userStories.length > 0) {
      addHeading("User Stories & Acceptance Criteria", 14);
      data.userStories.forEach((s) => {
        addParagraph(s.story);
        addBulletList(s.acceptance_criteria ?? []);
      });
    }

    if (data.metrics.length > 0) {
      addHeading("Success Metrics", 14);
      data.metrics.forEach((m) => {
        addParagraph(`${m.name}: ${m.description} (Target: ${m.target})`);
      });
    }

    const safeFileName = data.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .slice(0, 50);

    doc.save(`${safeFileName || "wirepilot-plan"}.pdf`);
    setGenerating(false);
  }

  return (
    <button
      onClick={handleExport}
      disabled={generating}
      style={{
        padding: "0.5rem 1rem",
        borderRadius: 6,
        border: "1px solid #111",
        background: "#111",
        color: "#fff",
        cursor: "pointer",
        fontSize: "0.9rem",
      }}
    >
      {generating ? "Preparing PDF..." : "Export PDF"}
    </button>
  );
}
